[XmlWinEventLog:Microsoft-Windows-Sysmon/Operational]
REPORT-sysmon-eventid = sysmon_eventid
REPORT-sysmon-data = sysmon_data_fields

[XmlWinEventLog:Security]
REPORT-windows-eventid = sysmon_eventid
REPORT-windows-data = sysmon_data_fields
