[sysmon_eventid]
REGEX = <EventID(?:\s+[^>]*)?>(\d+)</EventID>
FORMAT = EventCode::$1

[sysmon_data_fields]
REGEX = <Data Name=["']([^"']+)["']>([^<]*)</Data>
FORMAT = $1::$2
MV_ADD = true
REPEAT_MATCH = true
